name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  build-and-test:
    name: "Execute build and run tests"
    runs-on: ubuntu-latest
    env:
      BASE_PATH: "/"
      NODE_ENV: "production"
      NEXT_PUBLIC_CHAIN_TYPE: testnet
      NEXT_PUBLIC_GRAPHQL_URL: "https://testnet-gql.cheqd.io/v1/graphql"
      NEXT_PUBLIC_GRAPHQL_WS: "wss://testnet-gql.cheqd.io/v1/graphql"
      NEXT_PUBLIC_RPC_WEBSOCKET: "wss://rpc.cheqd.network/websocket"
      PROJECT_NAME: web-cheqd
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Execute build"
        run: yarn build
      
      - name: "Execute tests"
        run: yarn run test
